name: Trivia Game Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  verify_code:
    runs-on: ubuntu-latest

    steps:
      - name: Setup environment
        run: |
          git config --global user.email "${{ vars.EMAIL }}"
          git config --global user.name "${{ vars.USERNAME }}"
          git config --global url.https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/.insteadOf https://github.com/

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node packages
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
